export const STUDENT = {
  profile: {
    name: "Manisha Naskar",
    mobile: "9748 5888 62",
    email: "whitelightofuniverse@gmail.com",
    password: "Manisha@2025",
    photo: "path/to/photo.jpg", // Placeholder
  },
  fees: [
    {
      semester: "Semester 1: DAP",
      totalAmount: 15100,
      payments: [
        {
          id: 1,
          details: "Admission",
          date: "24 Dec 2024",
          fees: 15000,
          lateFees: 10,
          total: 15010,
          status: "Paid",
          action: "View",
        },
        {
          id: 2,
          details: "Month Dec-24",
          date: "Sun 5th Dec 2024",
          fees: 1200,
          lateFees: 110,
          total: 1310,
          status: "Pending",
          action: "Pay Now",
        },
        {
          id: 3,
          details: "Month Jan-25",
          date: "Sun 5th Jan 2025",
          fees: 1200,
          lateFees: 10,
          total: 1210,
          status: "Pending",
          action: "Pay Now",
        },
      ],
    },
    {
      semester: "Semester 2: BCP",
      totalAmount: 12000,
      payments: [
        {
          id: 4,
          details: "Admission",
          date: "Pending",
          fees: 1500,
          lateFees: 10,
          total: 1510,
          status: "Pending",
          action: "Pay Now",
        },
        {
          id: 5,
          details: "Month Jan-25",
          date: "Sun 5th Jan 2025",
          fees: 1200,
          lateFees: 10,
          total: 1210,
          status: "Pending",
          action: "Pay Now",
        },
        {
          id: 6,
          details: "Month Feb-25",
          date: "Sun 5th Feb 2025",
          fees: 1200,
          lateFees: 10,
          total: 1210,
          status: "Pending",
          action: "Pay Now",
        },
        {
          id: 7,
          details: "Month Mar-25",
          date: "Sun 5th Mar 2025",
          fees: 1200,
          lateFees: 10,
          total: 1210,
          status: "Pending",
          action: "Pay Now",
        },
      ],
    },
    {
      semester: "Semester 3: MEP",
      totalAmount: 8000,
      payments: [
        {
          id: 8,
          details: "Admission",
          date: "Pending",
          fees: 1500,
          lateFees: 10,
          total: 1510,
          status: "Pending",
          action: "Pay Now",
        },
        {
          id: 9,
          details: "Month Aug-25",
          date: "Sun 5th Aug 2025",
          fees: 1200,
          lateFees: 10,
          total: 1210,
          status: "Pending",
          action: "Pay Now",
        },
        {
          id: 10,
          details: "Month Sep-25",
          date: "Sun 5th Sep 2025",
          fees: 1200,
          lateFees: 10,
          total: 1210,
          status: "Pending",
          action: "Pay Now",
        },
      ],
    },
  ],
  studyMaterials: [
    {
      id: 1,
      topic: "Introduction to Astrology",
      date: "01 Dec 2024",
      description:
        "Comprehensive guide covering the basic concepts of planets, signs, and houses. Ideal for beginners starting their journey into astrology.",
      downloadUrl: "#",
    },
    {
      id: 2,
      topic: "Understanding Zodiac Signs",
      date: "10 Dec 2024",
      description:
        "A deep dive into the 12 zodiac signs, their characteristics, elements, and modalities. Learn how they influence personality and destiny.",
      downloadUrl: "#",
    },
    {
      id: 3,
      topic: "Planetary Transits 2025",
      date: "01 Jan 2025",
      description:
        "Detailed analysis of major planetary movements in 2025 and their predicted impact on various ascendants.",
      downloadUrl: "#",
    },
  ],
  videos: [
    { id: 1, date: "12 Dec 2024", thumbnail: "path/to/thumb1.jpg" },
    { id: 2, date: "15 Dec 2024", thumbnail: "path/to/thumb2.jpg" },
    { id: 3, date: "18 Dec 2024", thumbnail: "path/to/thumb3.jpg" },
    { id: 4, date: "22 Dec 2024", thumbnail: "path/to/thumb4.jpg" },
    { id: 5, date: "25 Dec 2024", thumbnail: "path/to/thumb5.jpg" },
    { id: 6, date: "29 Dec 2024", thumbnail: "path/to/thumb6.jpg" },
    { id: 7, date: "02 Jan 2025", thumbnail: "path/to/thumb7.jpg" },
    { id: 8, date: "05 Jan 2025", thumbnail: "path/to/thumb8.jpg" },
    { id: 9, date: "08 Jan 2025", thumbnail: "path/to/thumb9.jpg" },
  ],
  reExamFees: [
    { id: 1, examName: "DKP", amount: 1500 },
    { id: 2, examName: "BKP", amount: 2000 },
    { id: 3, examName: "MKP", amount: 2500 },
    { id: 4, examName: "FKP", amount: 3000 },
  ],
};

// Re-export for potential backward compatibility if needed temporarily,
// but the plan is to update consumers immediately.
export const FEES_DATA = STUDENT.fees;
