import type { Metadata } from "next";
import { Courgette, Geist, Geist_Mono } from "next/font/google";

import { Amaranth } from "next/font/google";

import "./globals.css";
export const amaranth = Amaranth({
  weight: ["400", "700"], // Specify the weights you need
  subsets: ["latin"], // Specify necessary subsets
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const courgette = Courgette({
  subsets: ["latin"],
  weight: "400", // Courgette only has Regular
  variable: "--font-courgette",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  antialiased`}>{children}</body>
    </html>
  );
}
